import Authorization from "./Authorization"
import Auth from "./Authorization/Auth"
import CheckOtp from "./Authorization/CheckOtp"
import CheckPass from "./Authorization/CheckPass"
import ForgetPass from "./Authorization/ForgetPass"
import Home from "./Home"
import Products from "./Products"
import ProductsDetails from "./ProductsDetails"
import Cart from "./Cart"
import Profile from "./Profile"
import NotFound from "./NotFound"
import Favorite from "./Favorites"
export {Favorite,Authorization,Auth,CheckOtp,CheckPass,ForgetPass,Home,Products,ProductsDetails,Profile,Cart,NotFound}